apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: tommartensen/mocc-assignment-backend:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
        livenessProbe:
          httpGet:
            path: /ready
            port: 80
            httpHeaders:
            - name: CC-Ready
              value: Backend
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
            httpHeaders:
            - name: CC-Ready
              value: Backend
          initialDelaySeconds: 3
          periodSeconds: 3
