apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: tommartensen/mocc-assignment-frontend:latest
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 80
        livenessProbe:
          httpGet:
            path: /ready
            port: 80
            httpHeaders:
            - name: CC-Ready
              value: Frontend
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 80
            httpHeaders:
            - name: CC-Ready
              value: Frontend
          initialDelaySeconds: 3
          periodSeconds: 3
