version: '3'
services:
  frontend:
    image: tommartensen/mocc-assignment-frontend:latest
    ports:
    - 8080:80
    depends_on:
    - backend

  backend:
    image: tommartensen/mocc-assignment-backend:latest
